#install.packages("rvest")
#install.packages("stringr")
#install.packages("readr")
#install.packages("filesstrings")
#install.packages("readtext")
#install.packages("igraph")
#install.packages("sentiment.ai")
#install.packages("quanteda")


library(igraph)
library(rvest)
library(stringr)
library(readr)
library(filesstrings)
library(readtext)
library(sentiment.ai)
library(quanteda)
